name: Roljobs
favicon: null
layout_spectrum: 0.13527
typography_spectrum: 0.58856
title: ﻿Roljobs Technology Services Pvt Ltd
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4f5670'
    - '#fdfdfd'
    - '#282e3e'
    - '#bdceea'
    - '#000004'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
