name: Roljobs
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60813
title: Leaders in Social Media Recruitment™
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.19273520354181528
  rhythmicContrast: 0.75
purpose: []
